# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e7ff34956d434e6e420b61b491e33b05b9b71db12b3b648c36f73354d4040e1c1b0368702e19a60dc086cb47725f83b55384b4aa343b3b82c78183285d577c6

test:
  secret_key_base: 74b92c8f2a5033bb1d997cf9cb9f9b4bd406c294eb11e93563bdef91158bc1083c32e18e11861f0b9812023d3fc2c116f0102a2c4eca1d956b3d00447fd29c58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
